version: "3.8"
services:
  database:
    build: ./app/server
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
  client:
    build: ./app/client/
    ports:
      - "3000:3000"
    volumes:
      - ./app/client:/app/
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - database
# must specify named volumes (not anonymous / bind mounts)
volumes:
  data:
